...

diff --git a/.x-cmd/sync b/.x-cmd/sync
--- a/.x-cmd/sync
+++ b/.x-cmd/sync
@@ -1,16 +1,33 @@
 
+# repo_push(){
+#     local name="${1:?Provide name}"
+#     local url="${2:?Provide url}"
+#     git remote remove "$name" 2>/dev/null || true; git remote add "$name" "$url"
+#     if ! git push -u "$name" --all; then
+#         x:warn "Push In Force: git push -u -f $name --all"
+#         git push -u -f "$name" --all
+#     fi
+
+#     if ! git push -u "$name" --tags; then
+#         x:warn "Push In Force: git push -u -f $name --tags"
+#         git push -u -f "$name" --tags
+#     fi
+# }
+
 repo_push(){
     local name="${1:?Provide name}"
     local url="${2:?Provide url}"
-    git remote remove "$name" 2>/dev/null || true; git remote add "$name" "$url"
-    if ! git push -u "$name" --all; then
-        x:warn "Push In Force: git push -u -f $name --all"
-        git push -u -f "$name" --all
-    fi
+    git branch -r | grep -v '\->' | grep -E "^ +origin" | \
+        while read -r remote; do
+            git branch --track "${remote#origin/}" "$remote";
+        done
 
-    if ! git push -u "$name" --tags; then
-        x:warn "Push In Force: git push -u -f $name --tags"
-        git push -u -f "$name" --tags
+    git remote remove "$name" >&2;  git remote add "$name" "$url"
+    if git branch -r | grep -q ^; then      # to prevent sync the empty repository
+        git fetch origin
+        git pull origin
+        git push -u --all tgt
+        git push --force --tags tgt
     fi
 }
 
@@ -50,3 +67,21 @@ repo()(
 )
 
 repo "${CONCURRENCY:-10}"
+
+# (
+#         if cd "$src_repo"; then
+#             # for remote in $(git branch -r | grep -v '\->' | grep -E "^ +origin"); do git branch --track "$remote"; done
+#             git branch -r | grep -v '\->' | grep -E "^ +origin" | while read remote; do git branch --track "${remote#origin/}" "$remote"; done
+#             git remote remove tgt >&2 # Just in case
+#             git remote add tgt "$2"
+#             # to prevent sync the empty repository
+#             ( git branch -r | grep -q ^ ) && (
+#                 git fetch origin
+#                 git pull origin
+#                 git push -u --all tgt
+#                 git push --force --tags tgt
+#             )
+#         else
+#             "BUG ATTENTION: cd fail!!!!" >&2
+#         fi
+#     )
